/*
 * boot_source.h - the assembly source of the boot program, shown in the
 * editor at power-on. Written by programs/make_programs.c (see
 * randtone_source there); do not edit by hand.
 */
#ifndef BOOT_SOURCE_H
#define BOOT_SOURCE_H

#define BOOT_SOURCE_NAME "RANDTONE"

static const char BOOT_SOURCE[] =
    "; RANDTONE: three loops make a tone,\n"
    "; and the 1861 shows where N is.\n"
    "; Outer: a new random number N, on the\n"
    ";   displays. Its high nibble is a row\n"
    ";   and its low nibble a column of a\n"
    ";   16 x 16 grid of 4 x 8 pixel blocks.\n"
    "; Middle: toggles Q till the time is up.\n"
    "; Inner: waits N turns between toggles.\n"
    "; R7 counts every inner turn, so a note\n"
    "; lasts the same time for any N; it\n"
    "; ends when R7 high byte is 0 (MIDDLE).\n"
    "; The picture is only 16 lines of 8\n"
    "; bytes at 0400; the interrupt routine\n"
    "; shows each line 8 times. All code\n"
    "; that runs with the video on uses\n"
    "; two-cycle instructions only. The\n"
    "; blocks stay lit until IN is pressed.\n"
    "MIDDLE  EQU  #18\n"
    "PICHI   EQU  04     ; picture at 0400\n"
    "\n"
    "        ORG  0000\n"
    "        GHI  0      ; D = 0 (page 0)\n"
    "        PHI  1\n"
    "        PHI  2\n"
    "        PHI  3\n"
    "        PHI  6\n"
    "        LDI  ISR\n"
    "        PLO  1      ; R1: interrupt\n"
    "        LDI  F0\n"
    "        PLO  2      ; R2: N, and stack\n"
    "        LDI  MAIN\n"
    "        PLO  3      ; R3: main program\n"
    "        LDI  SHOW\n"
    "        PLO  6      ; R6: subroutine\n"
    "        LDI  PICHI\n"
    "        PHI  5      ; R5: the picture\n"
    "        SEX  2\n"
    "        INP  1      ; video on\n"
    "        LDI  F0\n"
    "        STR  2      ; the first N is F0\n"
    "        SEP  3      ; R0 is for the DMA\n"
    "\n"
    "; Outer loop. The carries make it a\n"
    "; sequence of all 256 values.\n"
    "MAIN:\n"
    "NEXT:   LDN  2\n"
    "        SMI  00     ; DF = 1 for the ADC\n"
    "        ADC\n"
    "        ADD\n"
    "        ADD\n"
    "        ADD\n"
    "        STR  2\n"
    "        OUT  4      ; N on the displays\n"
    "        DEC  2\n"
    "        SEP  6      ; light the block\n"
    "        LDI  MIDDLE\n"
    "        PHI  7\n"
    "\n"
    "; Middle loop: wait, then toggle Q.\n"
    "PERIOD: LDN  2\n"
    "WAIT:   SMI  01     ; the inner loop\n"
    "        DEC  7      ; counts every turn\n"
    "        BNZ  WAIT\n"
    "        BQ   QOFF   ; Q on: go to REQ\n"
    "        SEQ         ; Q off: turn it on\n"
    "        DB   38     ; and skip the REQ\n"
    "QOFF:   REQ\n"
    "        B4   ERASE  ; IN pressed: clear\n"
    "AGAIN:  GHI  7\n"
    "        BNZ  PERIOD\n"
    "        BR   NEXT   ; a new note\n"
    "\n"
    "; The IN button (the I key) clears the\n"
    "; whole picture, 128 bytes at 0400.\n"
    "ERASE:  LDI  00\n"
    "        PLO  5      ; R5 = 0400\n"
    "ERASE1: STR  5\n"
    "        INC  5\n"
    "        GLO  5\n"
    "        SHL         ; DF = bit 7: done\n"
    "        LDI  00\n"
    "        BNF  ERASE1\n"
    "        BR   AGAIN\n"
    "\n"
    "; Subroutine: light the block for N.\n"
    "; Its byte is at 0400 + N / 2, and the\n"
    "; nibble depends on N bit 0.\n"
    "SHOW:   LDN  2\n"
    "        SHR         ; DF = N bit 0\n"
    "        PLO  5\n"
    "        LDI  F0     ; the left nibble\n"
    "        BNF  LEFT\n"
    "        LDI  0F     ; or the right one\n"
    "LEFT:   SEX  5\n"
    "        OR\n"
    "        STR  5      ; set its pixels\n"
    "        SEX  2\n"
    "        SEP  3      ; back to MAIN\n"
    "        BR   SHOW   ; for the next call\n"
    "\n"
    "; The interrupt routine. It saves T and\n"
    "; D on the stack at R2, sets R0 to the\n"
    "; picture exactly 29 cycles after the\n"
    "; interrupt, and then rewinds R0 so\n"
    "; each picture line is shown 8 times.\n"
    "; The DMA takes 8 of the 14 cycles of a\n"
    "; line, leaving three two-cycle\n"
    "; instructions: PLO 0 puts R0 back to\n"
    "; the line's start (D) in lines 1 to 7\n"
    "; of each 8, and GLO 0 saves the next\n"
    "; start in line 8. The BN1 is in the\n"
    "; 2nd slot of line 8, where EF1 is low\n"
    "; only at the end of the picture. The\n"
    "; RET is just before ISR, which R1\n"
    "; points to.\n"
    "LINES:  SEX  2      ; line 8, slot 3\n"
    "LINE1:  PLO  0      ; line 1: rewind\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 2\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 3\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 4\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 5\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 6\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        PLO  0      ; line 7\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        GLO  0      ; line 8: go on\n"
    "        BN1  LINES  ; EF1 low: the end\n"
    "        LDXA\n"
    "        RET\n"
    "ISR:    DEC  2\n"
    "        SAV\n"
    "        DEC  2\n"
    "        STR  2\n"
    "        NOP         ; three cycles\n"
    "        LDI  PICHI\n"
    "        PHI  0\n"
    "        LDI  00\n"
    "        PLO  0      ; R0 = 0400, D = 0\n"
    "        SEX  2      ; four fillers,\n"
    "        SEX  2      ; two cycles each\n"
    "        SEX  2\n"
    "        SEX  2\n"
    "        BR   LINE1  ; the DMA starts\n"
    ;

#endif /* BOOT_SOURCE_H */
